MODEL:
  TYPE: eva02_cloth
  NAME: eva02_l_bio
  LOSS_TYPE: ['ce','triplet','clipBio','clipBioReverse']
  LAST_LAYER: 'clipFc'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NO_MARGIN: True
  CLIP_DIM: 768

DATA:
  IMG_HEIGHT: 224
  IMG_WIDTH: 224
  DATASET: 'prcc'
  SUMMERY_TEXT: true
  NOBIO_INDEX: '1*'
  TEXT_MODEL: 'EVA02-CLIP'
  NUM_INSTANCES: 4
  BATCH_SIZE: 16
  NUM_WORKERS: 1
  PIN_MEMORY: False

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 60
  BASE_LR: 2e-6
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 60
  LOG_PERIOD: 50
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  0.05
  WEIGHT_DECAY_BIAS: 0.05
  BIAS_LR_FACTOR: 2

TEST:
  WEIGHT: ''
  FEAT_NORM: 'yes'
  TYPE: 'image_only'
OUTPUT_DIR: './logs/prcc'


